/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package quanlynganhang.GUI.model.headerbar;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import quanlynganhang.GUI.FormPopupProfile;
import quanlynganhang.GUI.JFrameThongBao;
import quanlynganhang.GUI.model.glasspanepopup.DefaultOption;
import quanlynganhang.GUI.model.glasspanepopup.GlassPanePopup;

public class HeaderBar extends javax.swing.JPanel {

    /** Creates new form SearchBar */
    public HeaderBar() {
        initComponents();
        
        putClientProperty(FlatClientProperties.STYLE, ""
            + "background:$HeaderBar.background;");
        jPHeaderBar.putClientProperty(FlatClientProperties.STYLE, ""
            + "background:$HeaderBar.background;");
        jpWelcome.putClientProperty(FlatClientProperties.STYLE, ""
            + "background:$HeaderBar.background;");
        jpSearch.putClientProperty(FlatClientProperties.STYLE, ""
            + "background:$HeaderBar.background;");
        jpProfile.putClientProperty(FlatClientProperties.STYLE, ""
            + "background:$HeaderBar.background;");
        
        txtSearch.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Tìm kiếm trong menu");
        txtSearch.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_ICON, new FlatSVGIcon("quanlynganhang/icon/search_btn.svg"));
        txtSearch.setVisible(false);
    }
    
    public void setTitleName(String name) {
        lbPanelName.setText(name);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPHeaderBar = new javax.swing.JPanel();
        jpWelcome = new javax.swing.JPanel();
        lbPanelName = new javax.swing.JLabel();
        jpSearch = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jpProfile = new javax.swing.JPanel();
        btnProfile = new javax.swing.JButton();
        btnNotifi = new javax.swing.JButton();
        btnMessage = new javax.swing.JButton();
        btnMail = new javax.swing.JButton();
        btnShowSearch = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1017, 74));
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        setLayout(new java.awt.BorderLayout());

        lbPanelName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbPanelName.setForeground(new java.awt.Color(255, 255, 255));
        lbPanelName.setText("Trang chủ");

        javax.swing.GroupLayout jpWelcomeLayout = new javax.swing.GroupLayout(jpWelcome);
        jpWelcome.setLayout(jpWelcomeLayout);
        jpWelcomeLayout.setHorizontalGroup(
            jpWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpWelcomeLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(lbPanelName, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpWelcomeLayout.setVerticalGroup(
            jpWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpWelcomeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbPanelName)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpSearchLayout = new javax.swing.GroupLayout(jpSearch);
        jpSearch.setLayout(jpSearchLayout);
        jpSearchLayout.setHorizontalGroup(
            jpSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpSearchLayout.setVerticalGroup(
            jpSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSearchLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnProfile.setContentAreaFilled(false);
        btnProfile.setOpaque(false);
        btnProfile.setBorderPainted(false);
        btnProfile.setIcon(new FlatSVGIcon("quanlynganhang/icon/profile.svg")
        );
        btnProfile.setToolTipText("Thông tin người dùng");
        btnProfile.setBorderPainted(false);
        btnProfile.setContentAreaFilled(false);
        btnProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProfileMouseClicked(evt);
            }
        });

        btnNotifi.setIcon(new FlatSVGIcon("quanlynganhang/icon/have_notifi_btn.svg")
        );
        btnNotifi.setToolTipText("Thông báo");
        btnNotifi.setBorderPainted(false);
        btnNotifi.setContentAreaFilled(false);
        btnNotifi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNotifi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotifiActionPerformed(evt);
            }
        });

        btnMessage.setIcon(new FlatSVGIcon("quanlynganhang/icon/chat_btn.svg")
        );
        btnMessage.setToolTipText("Tin nhắn");
        btnMessage.setBorderPainted(false);
        btnMessage.setContentAreaFilled(false);
        btnMessage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnMail.setIcon(new FlatSVGIcon("quanlynganhang/icon/mail_btn.svg")
        );
        btnMail.setToolTipText("Email");
        btnMail.setBorderPainted(false);
        btnMail.setContentAreaFilled(false);
        btnMail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMailActionPerformed(evt);
            }
        });

        btnShowSearch.setIcon(new FlatSVGIcon("quanlynganhang/icon/show_search_btn.svg")
        );
        btnShowSearch.setToolTipText("Tìm kiếm");
        btnShowSearch.setBorderPainted(false);
        btnShowSearch.setContentAreaFilled(false);
        btnShowSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShowSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowSearchMouseClicked(evt);
            }
        });
        btnShowSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpProfileLayout = new javax.swing.GroupLayout(jpProfile);
        jpProfile.setLayout(jpProfileLayout);
        jpProfileLayout.setHorizontalGroup(
            jpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpProfileLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnShowSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMail, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNotifi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpProfileLayout.setVerticalGroup(
            jpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btnNotifi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnShowSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(btnProfile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPHeaderBarLayout = new javax.swing.GroupLayout(jPHeaderBar);
        jPHeaderBar.setLayout(jPHeaderBarLayout);
        jPHeaderBarLayout.setHorizontalGroup(
            jPHeaderBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPHeaderBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jpProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPHeaderBarLayout.setVerticalGroup(
            jPHeaderBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPHeaderBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPHeaderBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        add(jPHeaderBar, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formAncestorAdded

    private void btnProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfileMouseClicked
        GlassPanePopup.showPopup(new FormPopupProfile());
    }//GEN-LAST:event_btnProfileMouseClicked

    private void btnNotifiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotifiActionPerformed
        btnNotifi.setIcon(new FlatSVGIcon("quanlynganhang/icon/notifi_btn.svg"));
        JFrameThongBao thongbao = new JFrameThongBao();
        thongbao.setTitle("Thông báo");
        thongbao.setDefaultCloseOperation(JFrameThongBao.DISPOSE_ON_CLOSE);
        thongbao.setVisible(true);
    }//GEN-LAST:event_btnNotifiActionPerformed

    private void btnMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMailActionPerformed

    private void btnShowSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowSearchMouseClicked
        if(!txtSearch.isVisible()) {
            txtSearch.setVisible(true);
            revalidate();
        } else {
            txtSearch.setVisible(false);
            revalidate();
        }
    }//GEN-LAST:event_btnShowSearchMouseClicked

    private void btnShowSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowSearchActionPerformed

    }//GEN-LAST:event_btnShowSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMail;
    private javax.swing.JButton btnMessage;
    private javax.swing.JButton btnNotifi;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnShowSearch;
    private javax.swing.JPanel jPHeaderBar;
    private javax.swing.JPanel jpProfile;
    private javax.swing.JPanel jpSearch;
    private javax.swing.JPanel jpWelcome;
    private javax.swing.JLabel lbPanelName;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
