package quanlynganhang.GUI.adminUI;

import quanlynganhang.GUI.*;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import quanlynganhang.BUS.ChucVuBUS;
import quanlynganhang.DTO.ChucVuDTO;
import quanlynganhang.GUI.model.menubar.Menu;
import quanlynganhang.GUI.model.message.MessageBox;

/**
 *
 * @author THAI
 */
public class FormThemChucVu extends javax.swing.JPanel {

    private JFrameMoTaCotChucVu chuThich;
    private ChucVuBUS chucVuBUS;
    private int biXoa;

    public FormThemChucVu() {
        chucVuBUS = new ChucVuBUS();
        initComponents();
        initCustomUI();
        biXoa = 0;
        loadDSChucVu(biXoa);
    }

    private void initCustomUI() {
        txtSearchQuyen.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nhập mã / tên chức vụ cần tìm...");
    }

    public void loadDSChucVu(int biXoa) {
        DefaultTableModel model = (DefaultTableModel) jTableDSChucVu.getModel();
        model.setRowCount(0);

        Object[][] dataModel = chucVuBUS.doiSangObjectChucVu(biXoa);

        String[] title = {"Mã chức vụ", "Tên chức vụ", "Mô tả", "Admin", "Thong ke", "QLKH", "QLNV", "QLTKKH", "QLTKNV", "QLT", "QLGD", "QLGTK", "QLVV", "QLVTD"};
        model.setDataVector(dataModel, title);

        jTableDSChucVu.setDefaultEditor(Object.class, null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupGender = new javax.swing.ButtonGroup();
        ppmChucVu = new javax.swing.JPopupMenu();
        mnuSua = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuXoa = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txtSearchQuyen = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnInfoTable = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnDoiBang = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDSChucVu = new javax.swing.JTable();

        mnuSua.setText("Sửa");
        mnuSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSuaActionPerformed(evt);
            }
        });
        ppmChucVu.add(mnuSua);
        ppmChucVu.add(jSeparator2);

        mnuXoa.setForeground(new java.awt.Color(255, 0, 51));
        mnuXoa.setText("Xóa");
        mnuXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuXoaActionPerformed(evt);
            }
        });
        ppmChucVu.add(mnuXoa);

        setPreferredSize(new java.awt.Dimension(1132, 511));
        setLayout(new java.awt.BorderLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel17.setText("Danh sách thông tin chức vụ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 95, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(728, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jButton2.setIcon(new FlatSVGIcon("quanlynganhang/icon/search_btn.svg")
        );

        jButton3.setIcon(new FlatSVGIcon("quanlynganhang/icon/reload_btn.svg")
        );
        jButton3.setToolTipText("Tải lại bảng");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnInfoTable.setIcon(new FlatSVGIcon("quanlynganhang/icon/info_btn.svg")
        );
        btnInfoTable.setToolTipText("");
        btnInfoTable.setBorderPainted(false);
        btnInfoTable.setContentAreaFilled(false);
        btnInfoTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInfoTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoTableActionPerformed(evt);
            }
        });

        jButton1.setIcon(new FlatSVGIcon("quanlynganhang/icon/quyen_label.svg")
        );
        jButton1.setText("Thêm chức vụ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnDoiBang.setText("Xem các chức vụ đã bị xóa");
        btnDoiBang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiBangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearchQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addComponent(btnInfoTable, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDoiBang, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSearchQuyen, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInfoTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDoiBang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jTableDSChucVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã chức vụ", "Tên chức vụ", "Mô tả", "Admin", "Thong ke", "QL khách hàng", "QL nhân viên", "QL tk kh", "QL tk nv", "QL the", "Gửi TK", "Vay", "Tín dụng"
            }
        ));
        jTableDSChucVu.setComponentPopupMenu(ppmChucVu);
        jScrollPane2.setViewportView(jTableDSChucVu);

        jPanel6.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1132, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 1120, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel3.add(jPanel8, java.awt.BorderLayout.CENTER);

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JDialogThemChucVu themChucVu = new JDialogThemChucVu(null, true);
        themChucVu.setDefaultCloseOperation(JDialogThemChucVu.DISPOSE_ON_CLOSE);
        themChucVu.setVisible(true);
        biXoa = 1;
        btnDoiBangActionPerformed(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnInfoTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoTableActionPerformed
        if (chuThich == null) {
            chuThich = new JFrameMoTaCotChucVu();
            chuThich.setResizable(false);
            chuThich.setDefaultCloseOperation(JFrameMoTaCotChucVu.DISPOSE_ON_CLOSE);
        }

        chuThich.setExtendedState(JFrameMoTaCotChucVu.NORMAL);
        chuThich.setVisible(true);
    }//GEN-LAST:event_btnInfoTableActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        loadDSChucVu(biXoa);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnDoiBangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiBangActionPerformed
        if (biXoa == 0) {
            biXoa = 1;
            loadDSChucVu(biXoa);
            btnDoiBang.setText("Xem các chức vụ có hiệu lực");
        } else {
            biXoa = 0;
            loadDSChucVu(biXoa);
            btnDoiBang.setText("Xem các chức vụ đã bị xóa");
        }
    }//GEN-LAST:event_btnDoiBangActionPerformed

    private void mnuSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSuaActionPerformed
        int selectedRow = jTableDSChucVu.getSelectedRow();
        if (selectedRow == -1) {
            MessageBox.showErrorMessage(null, "Vui lòng chọn chức vụ trước khi sửa!");
            return;
        } else {
            if (biXoa == 1) {
                MessageBox.showErrorMessage(null, "Không thể sửa các chức vụ đã xóa!");
                return;
            } else {
                Object idObj = jTableDSChucVu.getValueAt(selectedRow, 0);
                if (idObj != null) {
                    int maChucVu = Integer.parseInt(idObj.toString());
                    ChucVuDTO chucVu = new ChucVuDTO();
                    chucVu = chucVuBUS.getChucVuById(maChucVu);
                    if (chucVu == null) {
                        MessageBox.showErrorMessage(null, "Mã chức vụ không tồn tại!");
                        return;
                    } else {
                        JDialogThemChucVu suaChucVu = new JDialogThemChucVu(null, true, chucVu);
                        suaChucVu.setDefaultCloseOperation(JDialogThemChucVu.DISPOSE_ON_CLOSE);
                        suaChucVu.setVisible(true);

                        biXoa = 1;
                        btnDoiBangActionPerformed(null);
                    }
                }
            }
        }
    }//GEN-LAST:event_mnuSuaActionPerformed

    private void mnuXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuXoaActionPerformed
        int selectedRow = jTableDSChucVu.getSelectedRow();
        if (selectedRow == -1) {
            MessageBox.showErrorMessage(null, "Vui lòng chọn chức vụ trước khi xóa!");
            return;
        } else {
            if (biXoa == 1) {
                MessageBox.showErrorMessage(null, "Tính năng đang cập nhật");
                return;
            } else {
                Object idObj = jTableDSChucVu.getValueAt(selectedRow, 0);
                if (idObj != null) {
                    if (MessageBox.showConfirmMessage(this, "Bạn có chắc chắn muốn xóa chức vụ này?") == JOptionPane.NO_OPTION) {
                        return;
                    }

                    int maChucVu = Integer.parseInt(idObj.toString());
                    boolean isDelete = chucVuBUS.deleteChucVu(maChucVu);
                    if (isDelete == false) {
                        MessageBox.showErrorMessage(null, "Xóa chức vụ thất bại!");
                        return;
                    } else {
                        MessageBox.showInformationMessage(null, "", "Xóa chức vụ thành công");

                        biXoa = 1;
                        btnDoiBangActionPerformed(null);
                    }
                }
            }
        }
    }//GEN-LAST:event_mnuXoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoiBang;
    private javax.swing.ButtonGroup btnGroupGender;
    private javax.swing.JButton btnInfoTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTable jTableDSChucVu;
    private javax.swing.JMenuItem mnuSua;
    private javax.swing.JMenuItem mnuXoa;
    private javax.swing.JPopupMenu ppmChucVu;
    private javax.swing.JTextField txtSearchQuyen;
    // End of variables declaration//GEN-END:variables
}
