/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlynganhang.GUI;

import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.fonts.roboto.FlatRobotoFont;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Font;
import javax.swing.UIManager;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author THAI
 */
public class JFrameThongBao extends javax.swing.JFrame {

    /** Creates new form JFrameThongBao */
    public JFrameThongBao() {
        initComponents();
        jPScroll.getViewport().setOpaque(false);
        jPScroll.setViewportBorder(null);
        jPThongBao.setLayout(new MigLayout("inset 0, fillx, wrap", "[fill]"));
        loadThongBao();
    }

    private void loadThongBao() {
        jPThongBao.add(new ItemThongBao("Thông báo về lịch nghỉ giỗ tổ Hùng Vương", "12/04/2024"));
        jPThongBao.add(new ItemThongBao("Thông báo về lịch nghỉ ngày Quốc tế lao động", "11/04/2024"));
        jPThongBao.add(new ItemThongBao("Thông báo về lịch nghỉ ngày Giải phóng Miền Nam", "11/04/2024"));
        jPThongBao.add(new ItemThongBao("Thông báo về việc mở thêm dịch vụ Mở thẻ kép", "10/04/2024"));
        jPThongBao.add(new ItemThongBao("Thông báo về việc mở thêm dịch vụ Gửi tiết kiệm tích lũy", "06/04/2024"));
        jPThongBao.add(new ItemThongBao("Thông báo về việc đóng khuyến mãi Miễn phí mở thẻ tín dụng quốc tế", "02/04/2024"));
        jPThongBao.add(new ItemThongBao("Thông báo về việc tăng lãi suất Gửi tiết kiệm trên 6 tháng", "29/03/2024"));
        jPThongBao.add(new ItemThongBao("Thông báo về việc đóng khuyến mãi Miễn phí duy trì thẻ ghi nợ nội địa", "15/03/2024"));
        jPThongBao.add(new ItemThongBao("Thông báo về lịch nghỉ ngày Quốc tế phụ nữ", "01/03/2024"));
        jPThongBao.add(new ItemThongBao("Thông báo về việc mở thêm Hạng thẻ tín dụng Diamond", "25/02/2024"));
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPScroll = new javax.swing.JScrollPane();
        jPThongBao = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 153, 255));
        jButton1.setText("<html><u>Xem tất cả</u></html>");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thông báo của ngân hàng");

        jPScroll.setBorder(null);
        jPScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPThongBao.setOpaque(false);

        javax.swing.GroupLayout jPThongBaoLayout = new javax.swing.GroupLayout(jPThongBao);
        jPThongBao.setLayout(jPThongBaoLayout);
        jPThongBaoLayout.setHorizontalGroup(
            jPThongBaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );
        jPThongBaoLayout.setVerticalGroup(
            jPThongBaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
        );

        jPScroll.setViewportView(jPThongBao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatRobotoFont.install();
        FlatLaf.registerCustomDefaultsSource("quanlynganhang.GUI.themes");
        UIManager.put("defaultFont", new Font(FlatRobotoFont.FAMILY, Font.PLAIN, 13));
        FlatMacLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jPScroll;
    private javax.swing.JPanel jPThongBao;
    // End of variables declaration//GEN-END:variables
}
